export const allRouterLink = {
    homeScreen: "/",
    registerUser: "/register",
    loginUser: "/login",
    changePassword: "/changePassword",
    forgotPassword: "/forgotPassword",
    resetPassword: "/resetPassword",
    admissionForm: "/admissionForm",
    admissionFees: "/admissionFees/",
    studentFeeCard: "/studentFeeCard/:student_id",
    documentUpload: "/documentUpload",
    viewDocuments: "/viewDocuments",
    subjectAssignment: "/subjectAssignment",
    allTeacherAssignment: "/allTeacherAssignment",
    attendance: "/attendance",
    classStudents: "/classStudents/:classLevel/:Year_level_id",
    directorProfile: '/directorProfile',
    officeStaffProfile: '/officeStaffProfile',
    guardianProfile: '/guardianProfile',
    teacherProfile: '/teacherProfile',
    studentProfile: '/studentProfile',
    teacherDashboard: '/teacherDashboard',
    guardianDashboard: '/guardianDashboard',
    studentDashboard: '/studentDashboard',
    guardianAttendanceRecord: '/guardianAttendanceRecord',
    studentAttendance:'/studentAttendance',
    directorDashboard: '/directorDashboard',
    feeSummary: '/feeSummary',
    feeDashboard: '/feeDashboard',
    attendanceRecord:'/attendanceRecord',
    fullAttendance:'/fullAttendance/:className',
    directorMarkHolidays:'/directorMarkHolidays',
    officeStaffDashboard: '/officeStaffDashboard',
    addmissionDetails: '/addmissionDetails',
    addmissionDetailsById: '/addmissionDetails/:id',
    editAddmisionDetails: '/editAddmisionDetails/:id',
    allClasses: '/allClasses',
    allStudentsperClass: '/allStudentsPerClass/:id',
    studentDetails: '/studentDetails/:id',
    updateStudentdetail:'/updateStudentdetail/:id',
    allStaffMembers: '/allStaffMembers',
    staffDetail: '/staffDetail/:type/:id',
    updateStaffDetails: '/staffdetail/update/:type/:id',
    myAttendance: '/myAttendance/:id',
    periodsByClass:'/periodsByClass',
    periodAssignment: "periodAssignment/:year_level_id",
    guardianChildren: "/guardianChildren",

    // all routes before this
    unAuthorized: '/unauthorized',
    notFound: "*"
}