export const allRouterLink = {
    homeScreen: "/",
    registerUser: "/register",
    loginUser: "/login",
    changePassword: "/changePassword",
    forgotPassword: "/forgotPassword",
    resetPassword: "/resetPassword",
    admissionForm: "/admissionForm",
    admissionFees: "/admissionFees/",
    documentUpload: "/documentUpload",
    subjectAssignment: "/subjectAssignment",
    allTeacherAssignment: "/allTeacherAssignment",
    attendance: "/attendance",
    classStudents: "/classStudents/:classLevel",
    directorProfile: '/directorProfile',
    officeStaffProfile: '/officeStaffProfile',
    guardianProfile: '/guardianProfile',
    teacherProfile: '/teacherProfile',
    studentProfile: '/studentProfile',
    teacherDashboard: '/teacherDashboard',
    guardianDashboard: '/guardianDashboard',
    directorDashboard: '/directorDashboard',
    officeStaffDashboard: '/officeStaffDashboard',
    unAuthorized: '/unauthorized',
    notFound: "*"
}